# db connector
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emr_sec?useSSL=false
    username: root
    password: Bassguitar1

# JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

# PORT
server:
  port: 8989

management:
  endpoints:
    web:
      exposure:
        include: "*"

  server:
    error:
      include-message: always

# LOGGING
  logging:
    file:
      name: mylog.log

# SECURITY
application:
  security:
    jwt:
      secret-key: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
      access-token-expiration: 86400000
      refresh-token-expiration: 604800000

