spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emr_sec?useSSL=false
    username: root
    password: Bassguitar1

  jpa.hibernate.ddl_auto: create


server:
  port: 8989

management:
  endpoints:
    web:
      exposure:
        include: "*"

#g:
#  level:
#    root: info
#    com:
#      abycode:
#        service: debug
#  path: logs
#  file: ${logging.path}/log.log
#  pattern:
#    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
#    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"